name: Mypy type checking

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13.2
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install project dependencies
        run: pip install -r requirements.txt

      - name: Run mypy type checks
        run: rm -rf .mypy_cache && mypy . --ignore-missing-imports